language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t markhary/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true markhary/udemy-docker-react npm run test
